export const SAVE_TRIVIA_QUESTIONS = 'SAVE_TRIVIA_QUESTIONS';
export const SAVE_PLAYER_INFO = 'SAVE_PLAYER_INFO';
export const NEW_REQUEST = 'NEW_REQUEST';
export const FAILED_REQUEST = 'FAILED_REQUEST';
export const GET_PLAYER_SCORE = 'GET_PLAYER_SCORE';
